name: saia_core
description: Systemic Artificial Intelligence Agent (SAIA) core models, use cases, and translation contracts.
version: 1.0.1
homepage: https://github.com/Open-Neom

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

